name: Release Pdf

on:
  pull_request:
    branches: [main]
    paths: "resume_short.md"
  workflow_dispatch:

jobs:
  release:
    name: Release PDF
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm install
      - run: npm run build:pdf
      - name: Create a draft release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ github.event.pull_request.title }}
          draft: true
          fail_on_unmatched_files: true
          files: resume_short.md
          name: Release ${{ github.ref }}
